name: axe
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.20
      uses: actions/setup-node@v1
      with:
        node-version: 12.20
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start & npx wait-on http://localhost:4200
    - name: Run axe
      run: |
        npm install -g @axe-core/cli -g
        axe http://localhost:4200 --exit